### ISSUE TITLE
Failed to load a language-coffee-script package grammar

### ISSUE THREAD

**Issue by BlakeChaseley** [atom/language-coffee-script#173]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown macOS version
**Thrown From**: [language-coffee-script](https://github.com/atom/language-coffee-script) package 0.50.0

### Stack Trace

Failed to load a language-coffee-script package grammar

```
At The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/oniguruma/build/Release/onig_scanner.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Applications/Atom.app/Contents/Resources/app.asar/node_modules/language-coffee-script/grammars/coffeescript.json

Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/oniguruma/build/Release/onig_scanner.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/oniguruma/src/oniguruma.js:3:21)
    at /app.asar/node_modules/oniguruma/src/oniguruma.js:116:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get__ref (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:122436)
    at get_OnigRegExp (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:122522)
    at new Grammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:123553)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:121330)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360115)
    at l.readFile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359786)
    at u (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:580454)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:581707
    at fs.read.error (ELECTRON_ASAR.js:573:9)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:460:17)
  at /app.asar/node_modules/language-coffee-script/grammars/coffeescript.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
kite 0.184.0 
script 3.26.0 
```

**Comment by Arcanemagus** [comment]
`language-coffee-script` is a bundled package, you should not be seeing this in a normal Atom installation. Did you install the package _additionally_ through the package manager or manually in some manner?

**Comment by Arcanemagus** [comment]
You are also running an out of date version of Atom, please update to v1.47.0.
