### ISSUE TITLE
Broken symlinks log errors

### ISSUE THREAD

**Issue by kevinsawicki** [atom/language-coffee-script#52]
Fuzzy finder is logging errors for any broken symlinks in the project

```
ENOENT: no such file or directory, stat '/Users/kevin/github/atom/node_modules/fs-plus/node_modules/.bin/rimraf'
    at Error (native)
    at fs.statSync (fs.js:846:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
    at Object.realpathSync (fs.js:1456:12)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:243:29)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/load-paths-handler.js:90:20
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by kevinsawicki** [comment]
Derp, wrong repo
